export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function CateringLayout({ children }) {
    return (
        <div className="flex justify-center w-full">
            {children}
        </div>
    );
}
