import "./globals.css";
import Navbar from "./components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-background`}
      >
        <div className="fixed w-screen top-0 z-50">
          <Navbar />
        </div>
        <div className="flex justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
